language: python
python:
    - pypy
before_script:
    - sudo chmod a+rwX /etc/passwd /etc/group /etc /usr
    - echo "portage:x:250:250:portage:/var/tmp/portage:/bin/false" >> /etc/passwd
    - echo "portage::250:portage,travis" >> /etc/group
    - git clone https://github.com/gentoo/gentoo-portage-rsync-mirror.git /usr/portage
    - mkdir -p /etc/portage distfiles
    - ln -s /usr/portage/profiles/base/ /etc/portage/make.profile
    - wget -O - "https://github.com/gentoo/portage/archive/master.tar.gz" | tar -xz
script:
    - ret=0; cx=0;
      python ../portage-*/bin/repoman full -v || ret=1;
      exit "${ret}"
